if (!require("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
if (!require('ComplexHeatmap')) 
  BiocManager::install('ComplexHeatmap')
if (!require('stringr')) 
  install.packages('stringr')
if (!require('SNFtool')) 
  install.packages('SNFtool')
if (!require('igraph')) 
  install.packages('igraph')
if (!require('readxl')) 
  install.packages('readxl')